### ISSUE TITLE
OutOfMemory while inferencing but not in training

### ISSUE THREAD

**Issue by mayhugotong** [FreddyBanana/Llama2-LoRA-Trainer#1]
Dear FreddyBanana,

Thank you for your contribution to Llama2-lora-trainer. I am training with BIT_8 and successfully finished the training of the model on A40 with the following parameters. 

CUDA_VISIBLE_DEVICES=2 python3 main.py 	--MICRO_BATCH_SIZE 16  --BATCH_SIZE 16 	--EPOCHS 50 	--LEARNING_RATE 5e-5 	--CONTEXT_LEN 1024 	--TARGET_LEN 128 	--LORA_R 16	--LORA_DROPOUT 0.2 	--MODEL_NAME "/llama-7b-hf" 	--OUTPUT_DIR "./output_model_16_8bit" 	--DATA_PATH "fine_tune_data/train_lora_trainer_16.json" 	--DATA_TYPE "json"  --SAVE_STEPS 1000  --BIT_8

However, the memory is not enough when I try to inference the model with BIT_8 even 45GB is enough for training, and the output shows the following.

Traceback (most recent call last):
  File "inference.py", line 12, in <module>
    model = LlamaForCausalLM.from_pretrained(
  File "/home/stud/liao/miniconda3/envs/gpt/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2819, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

Could you please have a quick look and any advice is appreciated!

**Comment by FreddyBanana** [comment]
Sorry, I have no idea about this.
I have tried the models “TheBloke/Llama-2-7B-fp16” and "meta-llama/Llama-2-13b-hf" for 8bit inference and it works.
